on:
  push:
    tags:
      - "!v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build WASM module
        run: |
          ./src/wasm_navdata_interface/scripts/run_docker_cmd.sh ./scripts/build.sh
      - name: Upload WASM module to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: navdata_interface.wasm
          path: ./src/wasm_navdata_interface/out/navdata_interface.wasm
