on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build WASM module
        run: |
          ./src/navdata_updater/scripts/run_docker_cmd.sh ./scripts/build.sh
      - name: Upload WASM module to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: navdata_updater.wasm
          path: ./src/navdata_updater/out/navdata_updater.wasm
