on:
  push:
    tags:
      - "v*-rc*"
      - "v*-alpha*"
      - "v*-beta*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build WASM module
        run: |
          ./src/wasm_navdata_interface/scripts/run_docker_cmd.sh ./scripts/build.sh
      - name: Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./src/wasm_navdata_interface/out/navdata_interface.wasm
          prerelease: true
